encryptionsalt: v1:Ouv5C+cy5mM=:v1:S1TyOKhY/UZKo3E8:TrdyaH29AQBpBS5Nd7V6sq0GuXaCmg==
config:
  demoFleet:defaultLocation: eastus
  demoFleet:targets:
    - id: demo-target-01
      tenantId: abe468b2-18bb-4dd2-90b9-5b8982337eb7
      subscriptionId: c0d51042-7d0a-41f7-b270-151e4c4ea263
      targetGroup: canary
      region: centralus
      environment: prod
      tier: gold
      customerName: Demo Customer A
      managedApplicationId: /subscriptions/c0d51042-7d0a-41f7-b270-151e4c4ea263/resourceGroups/rg-demo-ma-apps-a/providers/Microsoft.Solutions/applications/mappo-ma-target-01
    - id: demo-target-02
      tenantId: 5476530d-fba1-4cd5-b2c0-fa118c5ff36e
      subscriptionId: 1adaaa48-139a-477b-a8c8-0e6289d6d199
      targetGroup: prod
      region: eastus
      environment: prod
      tier: gold
      customerName: Demo Customer B
      managedApplicationId: /subscriptions/1adaaa48-139a-477b-a8c8-0e6289d6d199/resourceGroups/rg-demo-ma-apps-b/providers/Microsoft.Solutions/applications/mappo-ma-target-02
  demoFleet:existingManagedEnvironmentIdsBySubscription:
    c0d51042-7d0a-41f7-b270-151e4c4ea263: /subscriptions/c0d51042-7d0a-41f7-b270-151e4c4ea263/resourceGroups/rg-mappo-runtime-demo/providers/Microsoft.App/managedEnvironments/cae-mappo-runtime-demo
