config:
  appserviceFleet:defaultLocation: eastus
  appserviceFleet:targets:
    - id: appservice-target-01
      tenantId: "<customer-tenant-guid>"
      subscriptionId: "<customer-subscription-guid-1>"
      targetGroup: canary
      region: eastus
      environment: prod
      tier: gold
      customerName: "Demo Customer B"
    - id: appservice-target-02
      tenantId: "<customer-tenant-guid>"
      subscriptionId: "<customer-subscription-guid-2>"
      targetGroup: prod
      region: eastus
      environment: prod
      tier: gold
      customerName: "Demo Customer C"
