#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME_ENV_FILE_DEFAULT="${ROOT_DIR}/.data/mappo-runtime.env"
ENV_FILE_DEFAULT="${ROOT_DIR}/.data/mappo-publisher-acr.env"

subscription_id=""
resource_group=""
acr_name=""
sp_name=""
runtime_env_file="${RUNTIME_ENV_FILE_DEFAULT}"
env_file="${ENV_FILE_DEFAULT}"
secret_name="publisher-acr-pull"

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Creates a pull-only service principal for the publisher ACR and writes an env file.

Options:
  --subscription-id <id>     Subscription that owns the ACR (default: active az account)
  --resource-group <name>    Resource group containing the ACR (default: derive from runtime env)
  --acr-name <name>          Publisher ACR name (default: derive from runtime env)
  --sp-name <name>           Service principal display name (default: mappo-acr-pull-<timestamp>)
  --runtime-env-file <path>  Runtime env file used for defaults (default: ${RUNTIME_ENV_FILE_DEFAULT})
  --env-file <path>          Output env file path (default: ${ENV_FILE_DEFAULT})
  --secret-name <name>       Secret name passed to workloads (default: publisher-acr-pull)
  -h, --help                 Show help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --subscription-id)
      subscription_id="${2:-}"
      shift 2
      ;;
    --resource-group)
      resource_group="${2:-}"
      shift 2
      ;;
    --acr-name)
      acr_name="${2:-}"
      shift 2
      ;;
    --sp-name)
      sp_name="${2:-}"
      shift 2
      ;;
    --runtime-env-file)
      runtime_env_file="${2:-}"
      shift 2
      ;;
    --env-file)
      env_file="${2:-}"
      shift 2
      ;;
    --secret-name)
      secret_name="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "azure-acr-pull-bootstrap: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if ! command -v az >/dev/null 2>&1; then
  echo "azure-acr-pull-bootstrap: Azure CLI is required." >&2
  exit 1
fi

if ! az account show --only-show-errors >/dev/null 2>&1; then
  echo "azure-acr-pull-bootstrap: no active Azure login. Run 'az login' first." >&2
  exit 1
fi

if [[ -f "${runtime_env_file}" ]]; then
  set -a
  source "${runtime_env_file}"
  set +a
fi

if [[ -z "${subscription_id}" ]]; then
  subscription_id="${MAPPO_RUNTIME_SUBSCRIPTION_ID:-}"
fi
if [[ -z "${resource_group}" ]]; then
  resource_group="${MAPPO_RUNTIME_RESOURCE_GROUP:-}"
fi
if [[ -z "${acr_name}" ]]; then
  acr_name="${MAPPO_RUNTIME_ACR_NAME:-}"
fi

if [[ -z "${subscription_id}" ]]; then
  subscription_id="$(az account show --query id -o tsv)"
fi
if [[ -z "${acr_name}" ]]; then
  echo "azure-acr-pull-bootstrap: set --acr-name or populate ${runtime_env_file}." >&2
  exit 1
fi
if [[ -z "${sp_name}" ]]; then
  sp_name="mappo-acr-pull-$(date +%Y%m%d%H%M%S)"
fi

az account set --subscription "${subscription_id}"

acr_id_args=(--name "${acr_name}")
if [[ -n "${resource_group}" ]]; then
  acr_id_args+=(--resource-group "${resource_group}")
fi

acr_id="$(az acr show "${acr_id_args[@]}" --query id -o tsv --only-show-errors)"
acr_login_server="$(az acr show "${acr_id_args[@]}" --query loginServer -o tsv --only-show-errors)"

mkdir -p "$(dirname "${env_file}")"

echo "azure-acr-pull-bootstrap: creating service principal '${sp_name}' for ${acr_name}"
sp_json="$(az ad sp create-for-rbac \
  --name "${sp_name}" \
  --role AcrPull \
  --scopes "${acr_id}" \
  --query '{clientId:appId,clientSecret:password,tenantId:tenant}' \
  -o json)"

credential_row="$("${ROOT_DIR}/scripts/run_tooling.sh" \
  azure-script-support sp-credentials \
  --json "${sp_json}")"
IFS=$'\t' read -r client_id client_secret tenant_id <<< "${credential_row}"

if [[ -z "${client_id}" || -z "${client_secret}" || -z "${tenant_id}" ]]; then
  echo "azure-acr-pull-bootstrap: failed to resolve service principal credentials." >&2
  exit 1
fi

cat > "${env_file}" <<EOF
# Generated by scripts/azure_acr_pull_bootstrap.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
export MAPPO_PUBLISHER_ACR_SERVER='${acr_login_server}'
export MAPPO_PUBLISHER_ACR_PULL_CLIENT_ID='${client_id}'
export MAPPO_PUBLISHER_ACR_PULL_CLIENT_SECRET='${client_secret}'
export MAPPO_PUBLISHER_ACR_PULL_SECRET_NAME='${secret_name}'
export MAPPO_PUBLISHER_ACR_TENANT_ID='${tenant_id}'
export MAPPO_PUBLISHER_ACR_NAME='${acr_name}'
export MAPPO_PUBLISHER_ACR_ID='${acr_id}'
EOF

chmod 600 "${env_file}"

echo "azure-acr-pull-bootstrap: wrote ${env_file}"
echo "azure-acr-pull-bootstrap: acr_login_server=${acr_login_server}"
echo "azure-acr-pull-bootstrap: client_id=${client_id}"
echo "azure-acr-pull-bootstrap: next step: source ${env_file}"
