#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IAC_DIR="${ROOT_DIR}/infra/pulumi"
STACK="${PULUMI_STACK:-dev}"
ENV_FILE_DEFAULT="${ROOT_DIR}/.data/mappo-db.env"
ENV_FILE="${ENV_FILE_DEFAULT}"

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Exports managed Postgres connection settings from Pulumi stack outputs into an env file.

Options:
  --stack <name>      Pulumi stack name (default: \$PULUMI_STACK or dev)
  --env-file <path>   Output env file path (default: ${ENV_FILE_DEFAULT})
  -h, --help          Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stack)
      STACK="${2:-}"
      shift 2
      ;;
    --env-file)
      ENV_FILE="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "iac-export-db-env: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if ! command -v pulumi >/dev/null 2>&1; then
  echo "iac-export-db-env: pulumi CLI is required." >&2
  exit 1
fi

if [[ ! -d "${IAC_DIR}" ]]; then
  echo "iac-export-db-env: missing IaC directory: ${IAC_DIR}" >&2
  exit 1
fi

mkdir -p "$(dirname "${ENV_FILE}")"

outputs_json="$(
  cd "${IAC_DIR}"
  pulumi stack output --stack "${STACK}" --json --show-secrets
)"

python3 - <<'PY' "${outputs_json}" "${ENV_FILE}"
from __future__ import annotations

import json
import os
import pathlib
import sys
from datetime import datetime, timezone

outputs = json.loads(sys.argv[1])
env_file = pathlib.Path(sys.argv[2])

enabled = bool(outputs.get("controlPlanePostgresEnabled"))
if not enabled:
    print(
        "iac-export-db-env: managed Postgres is not enabled in this stack. "
        "Set mappo:controlPlanePostgresEnabled=true and run pulumi up first.",
        file=sys.stderr,
    )
    raise SystemExit(2)

required_keys = {
    "controlPlanePostgresHost": "host",
    "controlPlanePostgresPort": "port",
    "controlPlanePostgresDatabase": "database",
    "controlPlanePostgresConnectionUsername": "username",
    "controlPlanePostgresPassword": "password",
    "controlPlaneDatabaseUrl": "database_url",
}

resolved: dict[str, str] = {}
for output_key, label in required_keys.items():
    raw_value = outputs.get(output_key)
    value = "" if raw_value is None else str(raw_value).strip()
    if value == "":
        print(
            f"iac-export-db-env: missing Pulumi output '{output_key}' ({label}).",
            file=sys.stderr,
        )
        raise SystemExit(3)
    resolved[label] = value


def sh_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
content = "\n".join(
    [
        f"# Generated by scripts/iac_export_db_env.sh on {timestamp}",
        f"export MAPPO_DATABASE_URL={sh_quote(resolved['database_url'])}",
        f"export DATABASE_URL={sh_quote(resolved['database_url'])}",
        f"export MAPPO_DB_HOST={sh_quote(resolved['host'])}",
        f"export MAPPO_DB_PORT={sh_quote(resolved['port'])}",
        f"export MAPPO_DB_NAME={sh_quote(resolved['database'])}",
        f"export MAPPO_DB_USER={sh_quote(resolved['username'])}",
        f"export MAPPO_DB_PASSWORD={sh_quote(resolved['password'])}",
        "export MAPPO_DB_SSLMODE='require'",
        "",
    ]
)

env_file.write_text(content, encoding="utf-8")
os.chmod(env_file, 0o600)

print(f"iac-export-db-env: wrote {env_file}")
print(
    "iac-export-db-env: exported keys: MAPPO_DATABASE_URL, MAPPO_DB_HOST, MAPPO_DB_PORT, "
    "MAPPO_DB_NAME, MAPPO_DB_USER, MAPPO_DB_PASSWORD"
)
PY
