config:
  mappo:targetProfile: empty
  mappo:publisherPrincipalObjectIds:
    c0d51042-7d0a-41f7-b270-151e4c4ea263: f114f7af-c526-469b-8808-93df66d58d74
    1adaaa48-139a-477b-a8c8-0e6289d6d199: 012098f6-5df7-4193-a0b6-c95f6cfa6ea1
  mappo:definitionNamePrefix: mappo-ma-def-dual-demo
  mappo:definitionResourceGroupPrefix: rg-mappo-ma-def-dual-demo
  mappo:applicationResourceGroupPrefix: rg-mappo-ma-apps-dual-demo
  mappo:managedEnvironmentNamePrefix: cae-mappo-ma-dual-demo
  mappo:targets:
    - id: target-01
      tenantId: tenant-001
      subscriptionId: c0d51042-7d0a-41f7-b270-151e4c4ea263
      targetGroup: canary
      region: eastus
      tier: gold
      environment: demo
      managedApplicationName: mappo-ma-target-01
      managedResourceGroupName: rg-mappo-ma-mrg-target-01
      containerAppName: ca-mappo-ma-target-01
      tags:
        ring: canary
        tier: gold
        environment: demo
    - id: target-02
      tenantId: tenant-002
      subscriptionId: 1adaaa48-139a-477b-a8c8-0e6289d6d199
      targetGroup: canary
      region: eastus
      tier: gold
      environment: demo
      managedApplicationName: mappo-ma-target-02
      managedResourceGroupName: rg-mappo-ma-mrg-target-02
      containerAppName: ca-mappo-ma-target-02
      tags:
        ring: canary
        tier: gold
        environment: demo
encryptionsalt: v1:pKTEJPjPy1M=:v1:c9qT0Z0ZshO/Fn1I:43LEPcInHrDGzH1ikj42gYVqoF7IKg==
