encryptionsalt: v1:gI5/fcFysDk=:v1:xJnLCNybROu4rLI1:t9stZwTq33w76qKiqhjU4q1gS+WFCA==
config:
  mappo:controlPlanePostgresAdminPassword:
    secure: v1:RaXRU+4w4fMa1aQp:l/Nnr9qnj0IejrvTqiqCIqzXEHC5VAVDhbzyk7ZTR3NYfBdryRbeHk2WzzWn0Yv20klX
  mappo:targetProfile: empty
  mappo:targets: '[{"id":"target-01","tenantId":"abe468b2-18bb-4dd2-90b9-5b8982337eb7","subscriptionId":"c0d51042-7d0a-41f7-b270-151e4c4ea263","targetGroup":"canary","region":"eastus","tier":"gold","environment":"demo","tags":{"tier":"gold","environment":"demo","ring":"canary"}},{"id":"target-02","tenantId":"5476530d-fba1-4cd5-b2c0-fa118c5ff36e","subscriptionId":"1adaaa48-139a-477b-a8c8-0e6289d6d199","targetGroup":"prod","region":"eastus","tier":"gold","environment":"demo","tags":{"tier":"gold","environment":"demo","ring":"prod"}}]'
  mappo:publisherPrincipalObjectIds: '{"c0d51042-7d0a-41f7-b270-151e4c4ea263":"81d0af32-0c47-4347-8173-68cf31b06c93","1adaaa48-139a-477b-a8c8-0e6289d6d199":"b2741abf-aace-401b-95a5-d9a733f9be9c"}'
  mappo:defaultLocation: eastus
  mappo:controlPlaneSubscriptionId: c0d51042-7d0a-41f7-b270-151e4c4ea263
  mappo:controlPlaneLocation: centralus
  mappo:controlPlanePostgresEnabled: "true"
  mappo:controlPlanePostgresAllowedIpRanges: '["68.226.82.42"]'
