flyway.url=jdbc:postgresql://localhost:5432/mappo
flyway.user=txero
flyway.password=txero
flyway.locations=filesystem:/flyway/sql
flyway.schemas=public
flyway.connectRetries=5
flyway.cleanDisabled=false
