flyway.url=jdbc:postgresql://localhost:5433/mappo
flyway.user=mappo
flyway.password=mappo
flyway.locations=filesystem:/flyway/sql
flyway.schemas=public
flyway.connectRetries=5
flyway.cleanDisabled=false
