import type { components } from "@/lib/api/generated/schema";

export type CreateRunRequest = components["schemas"]["CreateRunRequest"];
export type AdminOnboardingSnapshotResponse = components["schemas"]["AdminOnboardingSnapshotResponse"];
export type DeleteTargetRegistrationResponse = components["schemas"]["DeleteTargetRegistrationResponse"];
export type ForwarderLogIngestRequest = components["schemas"]["ForwarderLogIngestRequest"];
export type ForwarderLogIngestResponse = components["schemas"]["ForwarderLogIngestResponse"];
export type ForwarderLogIngestStatus = components["schemas"]["ForwarderLogIngestStatus"];
export type ForwarderLogLevel = components["schemas"]["ForwarderLogLevel"];
export type ForwarderLogRecord = components["schemas"]["ForwarderLogRecord"];
export type MarketplaceEventIngestRequest = components["schemas"]["MarketplaceEventIngestRequest"];
export type MarketplaceEventIngestResponse = components["schemas"]["MarketplaceEventIngestResponse"];
export type MarketplaceEventRecord = components["schemas"]["MarketplaceEventRecord"];
export type MarketplaceEventStatus = components["schemas"]["MarketplaceEventStatus"];
export type Release = components["schemas"]["Release"];
export type RunDetail = components["schemas"]["RunDetail"];
export type RunStatus = components["schemas"]["RunStatus"];
export type RunSummary = components["schemas"]["RunSummary"];
export type StopPolicy = components["schemas"]["StopPolicy"];
export type StrategyMode = components["schemas"]["StrategyMode"];
export type StructuredError = components["schemas"]["StructuredError"];
export type Target = components["schemas"]["Target"];
export type TargetRegistrationRecord = components["schemas"]["TargetRegistrationRecord"];
export type TargetExecutionRecord = components["schemas"]["TargetExecutionRecord"];
export type TargetLogEvent = components["schemas"]["TargetLogEvent"];
export type TargetStage = components["schemas"]["TargetStage"];
export type TargetStageRecord = components["schemas"]["TargetStageRecord"];
export type UpdateTargetRegistrationRequest = components["schemas"]["UpdateTargetRegistrationRequest"];
